# 单机数据库的dockerfile，方便用户测试非分布式环境下的单机数据库
FROM golang:1.22-alpine AS builder

# 设置工作目录为项目根目录（注意路径层级）
WORKDIR /app

# 复制整个项目
COPY . .
WORKDIR /app/http/main

RUN go env -w GOPROXY=https://goproxy.cn,direct && \
    go mod tidy -C ../../ && \
    CGO_ENABLED=0 GOOS=linux go build -o http .&& \
    chmod +x http



# 运行时阶段：使用轻量级 Alpine 镜像
FROM alpine:latest

# 设置工作目录
WORKDIR /app

# 从构建阶段复制整个 ComDB 目录
COPY --from=builder /app /app

# 进入 raft/run 目录
WORKDIR /app/http

# 赋予可执行文件权限
RUN chmod +x http

# http端口在9090进行暴露，这个端口暴露固定就好了
EXPOSE 9090

# 设置容器启动命令
CMD ["./node"]
