// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: raft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 事务操作类型扩展
type OperationType int32

const (
	OperationType_OP_UNKNOWN             OperationType = 0
	OperationType_OP_PUT                 OperationType = 1
	OperationType_OP_DELETE              OperationType = 2
	OperationType_OP_COMPENSATION_PUT    OperationType = 3 // 补偿PUT操作
	OperationType_OP_COMPENSATION_DELETE OperationType = 4 // 补偿DELETE操作
	OperationType_OP_READ                OperationType = 5 // 事务的读取操作
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OP_UNKNOWN",
		1: "OP_PUT",
		2: "OP_DELETE",
		3: "OP_COMPENSATION_PUT",
		4: "OP_COMPENSATION_DELETE",
		5: "OP_READ",
	}
	OperationType_value = map[string]int32{
		"OP_UNKNOWN":             0,
		"OP_PUT":                 1,
		"OP_DELETE":              2,
		"OP_COMPENSATION_PUT":    3,
		"OP_COMPENSATION_DELETE": 4,
		"OP_READ":                5,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MsgHup                MessageType = 0  // Trigger election
	MessageType_MsgBeat               MessageType = 1  // Heartbeat
	MessageType_MsgProp               MessageType = 2  // Propose log entry
	MessageType_MsgApp                MessageType = 3  // Append log entries
	MessageType_MsgAppResp            MessageType = 4  // Response to append
	MessageType_MsgVote               MessageType = 5  // Request vote
	MessageType_MsgVoteResp           MessageType = 6  // Response to vote
	MessageType_MsgSnap               MessageType = 7  // Install snapshot
	MessageType_MsgHeartbeat          MessageType = 8  // Leader heartbeat
	MessageType_MsgHeartbeatResp      MessageType = 9  // Response to heartbeat
	MessageType_MsgCommitTxn          MessageType = 10 // Txn request
	MessageType_MsgCommitTxnResp      MessageType = 11 // Txn commit response
	MessageType_MsgCompensation       MessageType = 12 // Compensation txn trigger
	MessageType_MsgCommitConflict     MessageType = 13 // Conflict Message Request
	MessageType_MsgCommitConflictResp MessageType = 14 // Conflict message response
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MsgHup",
		1:  "MsgBeat",
		2:  "MsgProp",
		3:  "MsgApp",
		4:  "MsgAppResp",
		5:  "MsgVote",
		6:  "MsgVoteResp",
		7:  "MsgSnap",
		8:  "MsgHeartbeat",
		9:  "MsgHeartbeatResp",
		10: "MsgCommitTxn",
		11: "MsgCommitTxnResp",
		12: "MsgCompensation",
		13: "MsgCommitConflict",
		14: "MsgCommitConflictResp",
	}
	MessageType_value = map[string]int32{
		"MsgHup":                0,
		"MsgBeat":               1,
		"MsgProp":               2,
		"MsgApp":                3,
		"MsgAppResp":            4,
		"MsgVote":               5,
		"MsgVoteResp":           6,
		"MsgSnap":               7,
		"MsgHeartbeat":          8,
		"MsgHeartbeatResp":      9,
		"MsgCommitTxn":          10,
		"MsgCommitTxnResp":      11,
		"MsgCompensation":       12,
		"MsgCommitConflict":     13,
		"MsgCommitConflictResp": 14,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

// ---------------------------
// 新增枚举类型
// ---------------------------
type EntryType int32

const (
	EntryType_ENTRY_NORMAL           EntryType = 0
	EntryType_ENTRY_CONF_CHANGE      EntryType = 1
	EntryType_ENTRY_TXN              EntryType = 2
	EntryType_ENTRY_TXN_COMPENSATION EntryType = 3
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_NORMAL",
		1: "ENTRY_CONF_CHANGE",
		2: "ENTRY_TXN",
		3: "ENTRY_TXN_COMPENSATION",
	}
	EntryType_value = map[string]int32{
		"ENTRY_NORMAL":           0,
		"ENTRY_CONF_CHANGE":      1,
		"ENTRY_TXN":              2,
		"ENTRY_TXN_COMPENSATION": 3,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[2].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[2]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

type TransactionPhase int32

const (
	TransactionPhase_PHASE_UNKNOWN    TransactionPhase = 0
	TransactionPhase_PHASE_PREPARE    TransactionPhase = 1
	TransactionPhase_PHASE_COMMIT     TransactionPhase = 2
	TransactionPhase_PHASE_COMPENSATE TransactionPhase = 3
	TransactionPhase_PHASE_ACK        TransactionPhase = 4
)

// Enum value maps for TransactionPhase.
var (
	TransactionPhase_name = map[int32]string{
		0: "PHASE_UNKNOWN",
		1: "PHASE_PREPARE",
		2: "PHASE_COMMIT",
		3: "PHASE_COMPENSATE",
		4: "PHASE_ACK",
	}
	TransactionPhase_value = map[string]int32{
		"PHASE_UNKNOWN":    0,
		"PHASE_PREPARE":    1,
		"PHASE_COMMIT":     2,
		"PHASE_COMPENSATE": 3,
		"PHASE_ACK":        4,
	}
)

func (x TransactionPhase) Enum() *TransactionPhase {
	p := new(TransactionPhase)
	*p = x
	return p
}

func (x TransactionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[3].Descriptor()
}

func (TransactionPhase) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[3]
}

func (x TransactionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionPhase.Descriptor instead.
func (TransactionPhase) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{3}
}

// Raft message types
// 补偿触发指令
type CompensationTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalTxnId string                 `protobuf:"bytes,1,opt,name=original_txn_id,json=originalTxnId,proto3" json:"original_txn_id,omitempty"` // 原始事务ID
	TriggerTerm   uint64                 `protobuf:"varint,2,opt,name=trigger_term,json=triggerTerm,proto3" json:"trigger_term,omitempty"`        // 触发补偿的任期
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                      // 补偿原因(冲突/超时等)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompensationTrigger) Reset() {
	*x = CompensationTrigger{}
	mi := &file_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensationTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensationTrigger) ProtoMessage() {}

func (x *CompensationTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensationTrigger.ProtoReflect.Descriptor instead.
func (*CompensationTrigger) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

func (x *CompensationTrigger) GetOriginalTxnId() string {
	if x != nil {
		return x.OriginalTxnId
	}
	return ""
}

func (x *CompensationTrigger) GetTriggerTerm() uint64 {
	if x != nil {
		return x.TriggerTerm
	}
	return 0
}

func (x *CompensationTrigger) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Core data structures
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Term  uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type  string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // EntryNormal or EntryConfChange
	// Types that are valid to be assigned to Payload:
	//
	//	*Entry_RawData
	//	*Entry_Txn
	//	*Entry_Comp
	Payload isEntry_Payload `protobuf_oneof:"payload"`
	// 版本控制增强
	DataVersion   uint64 `protobuf:"varint,7,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	Data          []byte `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entry) GetPayload() isEntry_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Entry) GetRawData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Entry_RawData); ok {
			return x.RawData
		}
	}
	return nil
}

func (x *Entry) GetTxn() *TransactionPackage {
	if x != nil {
		if x, ok := x.Payload.(*Entry_Txn); ok {
			return x.Txn
		}
	}
	return nil
}

func (x *Entry) GetComp() *CompensationTrigger {
	if x != nil {
		if x, ok := x.Payload.(*Entry_Comp); ok {
			return x.Comp
		}
	}
	return nil
}

func (x *Entry) GetDataVersion() uint64 {
	if x != nil {
		return x.DataVersion
	}
	return 0
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type isEntry_Payload interface {
	isEntry_Payload()
}

type Entry_RawData struct {
	RawData []byte `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3,oneof"` // 原始数据负载
}

type Entry_Txn struct {
	Txn *TransactionPackage `protobuf:"bytes,5,opt,name=txn,proto3,oneof"` // 事务数据包
}

type Entry_Comp struct {
	Comp *CompensationTrigger `protobuf:"bytes,6,opt,name=comp,proto3,oneof"` // 补偿触发指令
}

func (*Entry_RawData) isEntry_Payload() {}

func (*Entry_Txn) isEntry_Payload() {}

func (*Entry_Comp) isEntry_Payload() {}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      *SnapshotMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Snapshot) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SnapshotMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfState     *ConfState             `protobuf:"bytes,1,opt,name=conf_state,json=confState,proto3" json:"conf_state,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	mi := &file_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotMetadata) GetConfState() *ConfState {
	if x != nil {
		return x.ConfState
	}
	return nil
}

func (x *SnapshotMetadata) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotMetadata) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type ConfState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voters        []uint64               `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	Learners      []uint64               `protobuf:"varint,2,rep,packed,name=learners,proto3" json:"learners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfState) Reset() {
	*x = ConfState{}
	mi := &file_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfState) ProtoMessage() {}

func (x *ConfState) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfState.ProtoReflect.Descriptor instead.
func (*ConfState) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{4}
}

func (x *ConfState) GetVoters() []uint64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *ConfState) GetLearners() []uint64 {
	if x != nil {
		return x.Learners
	}
	return nil
}

type ConfChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // ConfChangeAddNode, ConfChangeRemoveNode, etc.
	NodeId        uint64                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Context       []byte                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfChange) Reset() {
	*x = ConfChange{}
	mi := &file_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfChange) ProtoMessage() {}

func (x *ConfChange) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfChange.ProtoReflect.Descriptor instead.
func (*ConfChange) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{5}
}

func (x *ConfChange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfChange) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ConfChange) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

// 事务操作单元
type TxnOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	OpType        OperationType          `protobuf:"varint,3,opt,name=op_type,json=opType,proto3,enum=pb.OperationType" json:"op_type,omitempty"`
	Metadata      map[string][]byte      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnOperation) Reset() {
	*x = TxnOperation{}
	mi := &file_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnOperation) ProtoMessage() {}

func (x *TxnOperation) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnOperation.ProtoReflect.Descriptor instead.
func (*TxnOperation) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{6}
}

func (x *TxnOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TxnOperation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TxnOperation) GetOpType() OperationType {
	if x != nil {
		return x.OpType
	}
	return OperationType_OP_UNKNOWN
}

func (x *TxnOperation) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 完整事务包
type TransactionPackage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxnId           string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`                                // 全局唯一事务ID
	Timestamp       uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // 混合授时时间戳
	ExpectedVersion uint64                 `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // 用于MVCC的版本控制
	IsCompensation  bool                   `protobuf:"varint,4,opt,name=is_compensation,json=isCompensation,proto3" json:"is_compensation,omitempty"`    // 是否补偿事务
	Operations      []*TxnOperation        `protobuf:"bytes,5,rep,name=operations,proto3" json:"operations,omitempty"`
	CompensationOps []*TxnOperation        `protobuf:"bytes,6,rep,name=compensation_ops,json=compensationOps,proto3" json:"compensation_ops,omitempty"` // 预定义的补偿操作
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionPackage) Reset() {
	*x = TransactionPackage{}
	mi := &file_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionPackage) ProtoMessage() {}

func (x *TransactionPackage) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionPackage.ProtoReflect.Descriptor instead.
func (*TransactionPackage) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionPackage) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *TransactionPackage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionPackage) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *TransactionPackage) GetIsCompensation() bool {
	if x != nil {
		return x.IsCompensation
	}
	return false
}

func (x *TransactionPackage) GetOperations() []*TxnOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *TransactionPackage) GetCompensationOps() []*TxnOperation {
	if x != nil {
		return x.CompensationOps
	}
	return nil
}

type Message struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Type       MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=pb.MessageType" json:"type,omitempty"`
	To         uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	From       uint64                 `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Term       uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	Index      uint64                 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	Entries    []*Entry               `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries,omitempty"`
	Commit     uint64                 `protobuf:"varint,8,opt,name=commit,proto3" json:"commit,omitempty"`
	RejectHint uint64                 `protobuf:"varint,9,opt,name=rejectHint,proto3" json:"rejectHint,omitempty"`
	Snapshot   *Snapshot              `protobuf:"bytes,10,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Reject     bool                   `protobuf:"varint,11,opt,name=reject,proto3" json:"reject,omitempty"`
	Context    []byte                 `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
	LogTerm    uint64                 `protobuf:"varint,13,opt,name=logTerm,proto3" json:"logTerm,omitempty"`
	// 事务相关扩展
	TxnContextId  string              `protobuf:"bytes,14,opt,name=txn_context_id,json=txnContextId,proto3" json:"txn_context_id,omitempty"`             // 事务上下文ID
	TxnPhase      TransactionPhase    `protobuf:"varint,15,opt,name=txn_phase,json=txnPhase,proto3,enum=pb.TransactionPhase" json:"txn_phase,omitempty"` // 事务阶段
	TxnPackage    *TransactionPackage `protobuf:"bytes,16,opt,name=txn_package,json=txnPackage,proto3" json:"txn_package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{8}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MsgHup
}

func (x *Message) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Message) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Message) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *Message) GetRejectHint() uint64 {
	if x != nil {
		return x.RejectHint
	}
	return 0
}

func (x *Message) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Message) GetReject() bool {
	if x != nil {
		return x.Reject
	}
	return false
}

func (x *Message) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Message) GetLogTerm() uint64 {
	if x != nil {
		return x.LogTerm
	}
	return 0
}

func (x *Message) GetTxnContextId() string {
	if x != nil {
		return x.TxnContextId
	}
	return ""
}

func (x *Message) GetTxnPhase() TransactionPhase {
	if x != nil {
		return x.TxnPhase
	}
	return TransactionPhase_PHASE_UNKNOWN
}

func (x *Message) GetTxnPackage() *TransactionPackage {
	if x != nil {
		return x.TxnPackage
	}
	return nil
}

type TxnResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxnId           string                 `protobuf:"bytes,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	ConflictedNodes []uint64               `protobuf:"varint,3,rep,packed,name=conflicted_nodes,json=conflictedNodes,proto3" json:"conflicted_nodes,omitempty"`
	ErrorDetail     string                 `protobuf:"bytes,4,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TxnResponse) Reset() {
	*x = TxnResponse{}
	mi := &file_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResponse) ProtoMessage() {}

func (x *TxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResponse.ProtoReflect.Descriptor instead.
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{9}
}

func (x *TxnResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TxnResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *TxnResponse) GetConflictedNodes() []uint64 {
	if x != nil {
		return x.ConflictedNodes
	}
	return nil
}

func (x *TxnResponse) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

var File_raft_proto protoreflect.FileDescriptor

const file_raft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"raft.proto\x12\x02pb\"x\n" +
	"\x13CompensationTrigger\x12&\n" +
	"\x0foriginal_txn_id\x18\x01 \x01(\tR\roriginalTxnId\x12!\n" +
	"\ftrigger_term\x18\x02 \x01(\x04R\vtriggerTerm\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xff\x01\n" +
	"\x05Entry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\braw_data\x18\x04 \x01(\fH\x00R\arawData\x12*\n" +
	"\x03txn\x18\x05 \x01(\v2\x16.pb.TransactionPackageH\x00R\x03txn\x12-\n" +
	"\x04comp\x18\x06 \x01(\v2\x17.pb.CompensationTriggerH\x00R\x04comp\x12!\n" +
	"\fdata_version\x18\a \x01(\x04R\vdataVersion\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04dataB\t\n" +
	"\apayload\"P\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.pb.SnapshotMetadataR\bmetadata\"j\n" +
	"\x10SnapshotMetadata\x12,\n" +
	"\n" +
	"conf_state\x18\x01 \x01(\v2\r.pb.ConfStateR\tconfState\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\"?\n" +
	"\tConfState\x12\x16\n" +
	"\x06voters\x18\x01 \x03(\x04R\x06voters\x12\x1a\n" +
	"\blearners\x18\x02 \x03(\x04R\blearners\"S\n" +
	"\n" +
	"ConfChange\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x04R\x06nodeId\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontext\"\xdb\x01\n" +
	"\fTxnOperation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12*\n" +
	"\aop_type\x18\x03 \x01(\x0e2\x11.pb.OperationTypeR\x06opType\x12:\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1e.pb.TxnOperation.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x12TransactionPackage\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x04R\x0fexpectedVersion\x12'\n" +
	"\x0fis_compensation\x18\x04 \x01(\bR\x0eisCompensation\x120\n" +
	"\n" +
	"operations\x18\x05 \x03(\v2\x10.pb.TxnOperationR\n" +
	"operations\x12;\n" +
	"\x10compensation_ops\x18\x06 \x03(\v2\x10.pb.TxnOperationR\x0fcompensationOps\"\xe1\x03\n" +
	"\aMessage\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.pb.MessageTypeR\x04type\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x04R\x04from\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x04R\x05index\x12#\n" +
	"\aentries\x18\a \x03(\v2\t.pb.EntryR\aentries\x12\x16\n" +
	"\x06commit\x18\b \x01(\x04R\x06commit\x12\x1e\n" +
	"\n" +
	"rejectHint\x18\t \x01(\x04R\n" +
	"rejectHint\x12(\n" +
	"\bsnapshot\x18\n" +
	" \x01(\v2\f.pb.SnapshotR\bsnapshot\x12\x16\n" +
	"\x06reject\x18\v \x01(\bR\x06reject\x12\x18\n" +
	"\acontext\x18\f \x01(\fR\acontext\x12\x18\n" +
	"\alogTerm\x18\r \x01(\x04R\alogTerm\x12$\n" +
	"\x0etxn_context_id\x18\x0e \x01(\tR\ftxnContextId\x121\n" +
	"\ttxn_phase\x18\x0f \x01(\x0e2\x14.pb.TransactionPhaseR\btxnPhase\x127\n" +
	"\vtxn_package\x18\x10 \x01(\v2\x16.pb.TransactionPackageR\n" +
	"txnPackage\"\x8c\x01\n" +
	"\vTxnResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\tR\x05txnId\x12)\n" +
	"\x10conflicted_nodes\x18\x03 \x03(\x04R\x0fconflictedNodes\x12!\n" +
	"\ferror_detail\x18\x04 \x01(\tR\verrorDetail*|\n" +
	"\rOperationType\x12\x0e\n" +
	"\n" +
	"OP_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06OP_PUT\x10\x01\x12\r\n" +
	"\tOP_DELETE\x10\x02\x12\x17\n" +
	"\x13OP_COMPENSATION_PUT\x10\x03\x12\x1a\n" +
	"\x16OP_COMPENSATION_DELETE\x10\x04\x12\v\n" +
	"\aOP_READ\x10\x05*\x91\x02\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06MsgHup\x10\x00\x12\v\n" +
	"\aMsgBeat\x10\x01\x12\v\n" +
	"\aMsgProp\x10\x02\x12\n" +
	"\n" +
	"\x06MsgApp\x10\x03\x12\x0e\n" +
	"\n" +
	"MsgAppResp\x10\x04\x12\v\n" +
	"\aMsgVote\x10\x05\x12\x0f\n" +
	"\vMsgVoteResp\x10\x06\x12\v\n" +
	"\aMsgSnap\x10\a\x12\x10\n" +
	"\fMsgHeartbeat\x10\b\x12\x14\n" +
	"\x10MsgHeartbeatResp\x10\t\x12\x10\n" +
	"\fMsgCommitTxn\x10\n" +
	"\x12\x14\n" +
	"\x10MsgCommitTxnResp\x10\v\x12\x13\n" +
	"\x0fMsgCompensation\x10\f\x12\x15\n" +
	"\x11MsgCommitConflict\x10\r\x12\x19\n" +
	"\x15MsgCommitConflictResp\x10\x0e*_\n" +
	"\tEntryType\x12\x10\n" +
	"\fENTRY_NORMAL\x10\x00\x12\x15\n" +
	"\x11ENTRY_CONF_CHANGE\x10\x01\x12\r\n" +
	"\tENTRY_TXN\x10\x02\x12\x1a\n" +
	"\x16ENTRY_TXN_COMPENSATION\x10\x03*o\n" +
	"\x10TransactionPhase\x12\x11\n" +
	"\rPHASE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rPHASE_PREPARE\x10\x01\x12\x10\n" +
	"\fPHASE_COMMIT\x10\x02\x12\x14\n" +
	"\x10PHASE_COMPENSATE\x10\x03\x12\r\n" +
	"\tPHASE_ACK\x10\x042\xb0\x01\n" +
	"\x04Raft\x12'\n" +
	"\vSendMessage\x12\v.pb.Message\x1a\v.pb.Message\x12<\n" +
	"\x11CommitTransaction\x12\x16.pb.TransactionPackage\x1a\x0f.pb.TxnResponse\x12A\n" +
	"\x15CompensateTransaction\x12\x17.pb.CompensationTrigger\x1a\x0f.pb.TxnResponseB\x03Z\x01.b\x06proto3"

var (
	file_raft_proto_rawDescOnce sync.Once
	file_raft_proto_rawDescData []byte
)

func file_raft_proto_rawDescGZIP() []byte {
	file_raft_proto_rawDescOnce.Do(func() {
		file_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)))
	})
	return file_raft_proto_rawDescData
}

var file_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_raft_proto_goTypes = []any{
	(OperationType)(0),          // 0: pb.OperationType
	(MessageType)(0),            // 1: pb.MessageType
	(EntryType)(0),              // 2: pb.EntryType
	(TransactionPhase)(0),       // 3: pb.TransactionPhase
	(*CompensationTrigger)(nil), // 4: pb.CompensationTrigger
	(*Entry)(nil),               // 5: pb.Entry
	(*Snapshot)(nil),            // 6: pb.Snapshot
	(*SnapshotMetadata)(nil),    // 7: pb.SnapshotMetadata
	(*ConfState)(nil),           // 8: pb.ConfState
	(*ConfChange)(nil),          // 9: pb.ConfChange
	(*TxnOperation)(nil),        // 10: pb.TxnOperation
	(*TransactionPackage)(nil),  // 11: pb.TransactionPackage
	(*Message)(nil),             // 12: pb.Message
	(*TxnResponse)(nil),         // 13: pb.TxnResponse
	nil,                         // 14: pb.TxnOperation.MetadataEntry
}
var file_raft_proto_depIdxs = []int32{
	11, // 0: pb.Entry.txn:type_name -> pb.TransactionPackage
	4,  // 1: pb.Entry.comp:type_name -> pb.CompensationTrigger
	7,  // 2: pb.Snapshot.metadata:type_name -> pb.SnapshotMetadata
	8,  // 3: pb.SnapshotMetadata.conf_state:type_name -> pb.ConfState
	0,  // 4: pb.TxnOperation.op_type:type_name -> pb.OperationType
	14, // 5: pb.TxnOperation.metadata:type_name -> pb.TxnOperation.MetadataEntry
	10, // 6: pb.TransactionPackage.operations:type_name -> pb.TxnOperation
	10, // 7: pb.TransactionPackage.compensation_ops:type_name -> pb.TxnOperation
	1,  // 8: pb.Message.type:type_name -> pb.MessageType
	5,  // 9: pb.Message.entries:type_name -> pb.Entry
	6,  // 10: pb.Message.snapshot:type_name -> pb.Snapshot
	3,  // 11: pb.Message.txn_phase:type_name -> pb.TransactionPhase
	11, // 12: pb.Message.txn_package:type_name -> pb.TransactionPackage
	12, // 13: pb.Raft.SendMessage:input_type -> pb.Message
	11, // 14: pb.Raft.CommitTransaction:input_type -> pb.TransactionPackage
	4,  // 15: pb.Raft.CompensateTransaction:input_type -> pb.CompensationTrigger
	12, // 16: pb.Raft.SendMessage:output_type -> pb.Message
	13, // 17: pb.Raft.CommitTransaction:output_type -> pb.TxnResponse
	13, // 18: pb.Raft.CompensateTransaction:output_type -> pb.TxnResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_raft_proto_init() }
func file_raft_proto_init() {
	if File_raft_proto != nil {
		return
	}
	file_raft_proto_msgTypes[1].OneofWrappers = []any{
		(*Entry_RawData)(nil),
		(*Entry_Txn)(nil),
		(*Entry_Comp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_proto_goTypes,
		DependencyIndexes: file_raft_proto_depIdxs,
		EnumInfos:         file_raft_proto_enumTypes,
		MessageInfos:      file_raft_proto_msgTypes,
	}.Build()
	File_raft_proto = out.File
	file_raft_proto_goTypes = nil
	file_raft_proto_depIdxs = nil
}
